In [1]:
import numpy as np
positions = np.loadtxt("/ceph/bmaier/delight/share/TraceSimulator/position_MMC.dat")
print(positions)


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00 -1.9530000e+03]
 [ 1.0000000e+00  9.8000000e+01  0.0000000e+00 -1.9530000e+03]
 [ 2.0000000e+00  6.9296460e+01  6.9296460e+01 -1.9530000e+03]
 [ 3.0000000e+00  0.0000000e+00  9.8000000e+01 -1.9530000e+03]
 [ 4.0000000e+00 -6.9296460e+01  6.9296460e+01 -1.9530000e+03]
 [ 5.0000000e+00 -9.8000000e+01  0.0000000e+00 -1.9530000e+03]
 [ 6.0000000e+00 -6.9296460e+01 -6.9296460e+01 -1.9530000e+03]
 [ 7.0000000e+00 -0.0000000e+00 -9.8000000e+01 -1.9530000e+03]
 [ 8.0000000e+00  6.9296460e+01 -6.9296460e+01 -1.9530000e+03]
 [ 1.0000000e+03  1.4000000e+02  0.0000000e+00 -1.9160000e+03]
 [ 1.0010000e+03  1.2124356e+02  7.0000000e+01 -1.9160000e+03]
 [ 1.0020000e+03  7.0000000e+01  1.2124356e+02 -1.9160000e+03]
 [ 1.0030000e+03  0.0000000e+00  1.4000000e+02 -1.9160000e+03]
 [ 1.0040000e+03 -7.0000000e+01  1.2124356e+02 -1.9160000e+03]
 [ 1.0050000e+03 -1.2124356e+02  7.0000000e+01 -1.9160000e+03]
 [ 1.0060000e+03 -1.4000000e+02  0.0000000e+00 -1.91600

In [2]:
positions[45:]

array([[ 2000.     ,     0.     ,     0.     , -1700.5    ],
       [ 2001.     ,    94.     ,     0.     , -1700.5    ],
       [ 2002.     ,    66.46804,    66.46804, -1700.5    ],
       [ 2003.     ,     0.     ,    94.     , -1700.5    ],
       [ 2004.     ,   -66.46804,    66.46804, -1700.5    ],
       [ 2005.     ,   -94.     ,     0.     , -1700.5    ],
       [ 2006.     ,   -66.46804,   -66.46804, -1700.5    ],
       [ 2007.     ,    -0.     ,   -94.     , -1700.5    ],
       [ 2008.     ,    66.46804,   -66.46804, -1700.5    ]])